#!/usr/bin/env bash
#What type of network a computer in local is conne#cted to?
3
#What type of network could connect an office in o#ne building to another office in a building a few#streets away?
2
#What network do you use when you browse www.googl#e.com from your smartphone (not connected to the #Wifi)?
1
