#!/usr/bin/env bash
#to ping an id address passed in as argument
if [[ $1 == ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
then
	ping -c 5 "1"
else
	echo "usage: 5_is_the_host_on_the_network {IP_ADDRESS}"
fi
