#!/usr/bin/env bash
#to retrieve the list of active IP addresse
active_ips=$(ip -4 addr show | grep inet | awk '{print $2}' | cut '/' -f1)

#to display active ip addresses
echo "active IPv4 addresses 4:"
echo "active_ips"
